package com.api.spring.repository;

import com.api.spring.entidades.Cidade;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

/*
    CLASSE RESPONSAVEL POR SE COMUNICAR COM NOSSO BANCO DE DADOS.
    É NECESSARIO EXTENDER A CLASSE DO JPA DE NOME JpaRepository
    JpaRepository ELE É RESPONSAVEL POR REALIZAR A CONEXAO COM O BANCO DE DADOS
    E TAMBEM POSSUI OS METODO BASICOS PRONTOS DE UM CRUD
    JpaRepository<Cidade, Long> -> PRIMEIRO PARAMETRO O OBJETO QUE DEVE SER PERSISTIDO
    NO BANCO DE DADOS, SEGUNDO PARAMETRO TIPO DO ID A SER MANIPULADO
    O TIPO DO ID DEVE SER INFORMADO POIS É ATRAVÉS DESSE TIPO QUE OPERAÇÕES COMO BUSCAR POR ID
    OU DELETAR POR ID CONSEGUEM FAZER VERIFICAÇÃO DE TIPAGEM DO ATRIBUTO E CONSEQUENTEMENTE A BUSCA
 */

@Repository
public interface CidadeRepository extends JpaRepository<Cidade, Long> {

    /*
    REALIZA UMA BUSCA NO BANCO COM O FILTRO SENDO O CODIGO IBGE DE UMA CIDADE
    O MOTIVO DO RETORNO DA PUSCA SER UM OPTIONAL É PELO DE O USUARIO FORNECER O
    CODIGO IBGE PARA BUSCA, O OPTIONAL SERVE PARA TRATARMOS CASO NENHUM DADO SEJA
    RETORNADO PELA BUSCA
     */
    Optional<Cidade> findByIbge(Integer ibge);


    /*
    BUSCA PELOS 10 PRIMEIROS NOMES ENVIADOS POR PARAMETRO, BUSCA ESSA REALIZADA ATRAVÉS DA
    METODOLOGIA ONDE O NOME INFORMADO DEVE ESTAR CONTIDO NO NOME DA CIDADE E IGNORAMOS O
    FORMATO(CASE) DIGITADO PELO USUARIO
     */
    List<Cidade> findFirst10ByNomeContainingIgnoreCase(String nome);

//   MÉTODO NATIVO PARA LISTAR TODAS AS CIDADES
//    @Query(value = "SELECT * FROM cidade", nativeQuery = true)
//    List<Cidade> listarCidades();
}
